config/routes.rb
PersonalRailsSite::Application.routes.draw do
  get "posts/index"
  get "posts/show"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :posts
  resources :pages

  root 'pages#index'

  %w[about contact cv].each do |page|
    get page, controller: 'pages', action: page
  end  

  %w[about portfolio].each do |page|
    get page, controller: 'pages', action: page
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessible :email, :password, :password_confirmation
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
	attr_accessible :title, :slug, :description
	has_many :posts
end

app/models/page.rb
class Page < ActiveRecord::Base
	attr_accessible :title, :slug, :blurb, :content
	validates :title, presence: true, length: { minimum: 5}
	validates :slug, presence: true, format: { with: /\A[a-zA-Z-]+\z/,
						message: "Only letters allowed"}
	validates :content, presence: true, length: { minimum: 100 }
end

app/models/post.rb
class Post < ActiveRecord::Base
	attr_accessible :title, :slug, :blurb, :content, :category_id, :image
	belongs_to :category
	scope :rails, -> { where(category_id: 1)}
	extend FriendlyId
	friendly_id :title, use: [:slugged, :finders]
	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_filter :configure_permitted_parameters, if: :devise_controller?

  # protected

  # def configure_permited_parameters
  # 	devise_parameter_sanitizer.for(:sign_up) << :username
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :set_page, only: [:show, :edit, :update, :destroy]

  def index
  	@pages = Page.find(1)
  end

  def about
    @page = Page.find(2)
  end

  def contact
  end

  def create
  	@page = Page.new(page_params)
  	@page.save
  	redirect_to action: :show, id: @page.id
  end

  def new
  	@page = Page.new
  end

  def portfolio
  end
  
  def show
  end

  private
  	# Use callbacks to share common setup or constraints between actions
  	def set_page
  		@page = Page.find(params[:id])
  	end

  	#Never trust parameters from outside, only allow the white list through.
  	def page_params
  		params.require(:page).permit(:title, :slug, :content)
  	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all
  	@latest = Post.last
  end

  def show
  	@post = Post.friendly.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def nav_link(link_text, link_path, force_active = false)
		class_name = (force_active || current_page?(link_path)) ? 'active' : ''
		content_tag(:li, :class => class_name) do
			link_to link_text, link_path
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Andrew Jorczak</title>
  <%= metamagic title: "Andrew Jorczak", 
                description: "Personal Website for Andrew Jorczak: Web Developer, Actor",
                keywords: %w(web developer ruby rails Ruby On Rails Jorczak Chicago Actor Theatre) %>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p class="notice"> <%= notice %></p>
	<p class="alert"> <%= alert %></p>
<%= yield %>

</body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
<head>
<%= metamagic title: "Andrew Jorczak, Web Developer, Actor", 
							description: "Personal Website for Andrew Jorczak",
							keywords: %w(chicago actor ruby rails javascript jquery) %>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
  <%= stylesheet_link_tag    "pages", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="masthead">
    <h3 class="muted">Andrew Jorczak: Actor, Web Developer</h3>
  <div class="navbar navbar-default">
    <div class="navbar-header">
      <div class="container">
        <div class="container">
          <ul class="nav navbar-nav">
            <%= nav_link 'Home', root_path %>
            <%= nav_link 'About', about_path %>
            <%= nav_link 'Portfolio', portfolio_path %>
            <%= nav_link 'Blog', posts_path %>
          </ul> 
        </div>
      </div>
    </div>
  </div><!-- /.navbar -->
</div>
  <%= yield %>
  <hr>
  <div class="footer">
    <p>&copy; Andrew Jorczak 2013</p>
  </div>
</div> <!-- /container -->
</body>
</html>

app/views/layouts/posts.html.erb
<!DOCTYPE html>
<html>
<head>
<%= metamagic title: "Andrew Jorczak, Web Developer, Actor", 
              description: "Personal Website for Andrew Jorczak",
              keywords: %w(chicago actor ruby rails javascript jquery) %>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
  <%= stylesheet_link_tag    "posts", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="masthead">
    <h3 class="muted">Andrew Jorczak: Actor, Web Developer</h3>
      <div class="navbar navbar-default">
        <div class="navbar-header">
          <div class="container">
            <ul class="nav navbar-nav">
              <%= nav_link 'Home', root_path %>
              <%= nav_link 'About', about_path %>
              <%= nav_link 'Portfolio', portfolio_path %>
              <%= nav_link 'Blog', posts_path, true %>
            </ul> </div>
      </div>
    </div><!-- /.navbar -->
  </div>
    <%= yield %>
    <hr />
  <div class="footer">
    <p>&copy; Andrew Jorczak 2013</p>
  </div>
</div> <!-- /container -->

</body>
</html>

app/views/pages/about.html.erb
<% meta :title => "Andrew Jorczak",
				:description => "Andrew Jorczak's personal site",
				:keywords => %w(rails ruby on rails Rails) 
%>

<div class="row">
    <div class="col-md-9 col-lg-offset-2">
         <h3>Hi I'm Andrew</h3>
    </div>
</div>
<div class="row">
    <div class="col-md-8">
    	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
        non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		<p> <%= @page.content.html_safe %></p>
		</div>
    <div class="col-md-4"> <%= render "partials/twitter" %> </div>
</div>

app/views/pages/index.html.erb
<% meta :title => "Andrew Jorczak",
				:description => "Andrew Jorczak's personal site",
				:keywords => %w(rails ruby on rails Rails) 
%>

app/views/pages/new.html.erb
<% meta :title => "Andrew Jorczak",
				:description => "Andrew Jorczak's personal site",
				:keywords => %w(rails ruby on rails Rails) 
%>


<%= form_for(@page) do |f| %>

	<p>
		<%= f.label :title %><br/>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :slug %><br/>
		<%= f.text_field  :slug %>
	</p>
	<p>
		<%= f.label :content %> <br/>
		<%= f.text_field :content %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/pages/portfolio.html.erb
<div class="row">
    <div class="col-md-5" style="font-size: 12px;">
			<div id="tabs">
			  <ul>
			    <li><a href="#tabs-1">Nunc tincidunt</a></li>
			    <li><a href="#tabs-2">Proin dolor</a></li>
			    <li><a href="#tabs-3">Aenean lacinia</a></li>
			  </ul>
			  <div id="tabs-1">
			    <p>Tab content.</p>
			  </div>
			  <div id="tabs-2">
			    <p>Tab content.</p>
			   </div>
			   <div id="tabs-3">
			    <p>Tab content</p>
			   </div>
			</div>
    </div>
    <div class="col-md-4">content here</div>
</div>

app/views/pages/show.html.erb
<% meta :title => "Andrew Jorczak",
				:description => "Andrew Jorczak's personal site",
				:keywords => %w(rails ruby on rails Rails) 
%>

<p>
	<strong>Title</strong>
	<%= @page.title %>
</p>

<p>
	<strong>Slug</strong>
	<%= @page.slug %>
</p>

<p>
	<strong>Content:</strong>
	<%= @page.content %>
</p>

app/views/partials/_twitter.html.erb
<a class="twitter-timeline" href="https://twitter.com/andrewjorczak" data-widget-id="415613888676110336">Tweets by @andrewjorczak</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/posts/index.html.erb
<% meta :title => "Andrew Jorczak",
				:description => "Andrew Jorczak's personal site",
				:keywords => %w(rails ruby on rails Rails) 
%>

<div class="hero-unit">
	<h2>Latest post: <%= @latest.title %> </h2>
	<p> <%= @latest.blurb %> </p>
	<p>
		<%= link_to 'Read Post', @latest, :class => "btn btn-primary btn-large" %>
	</p>
</div>
<h1>Posts</h1>
<table clas="table table-bordered">
	<% @posts.each do |post| %>
		<tr>
			<td style="width:100px;"> <%= image_tag post.image_url(:thumb).to_s %></td>
			<td>
				<div>
					<strong><%= post.title %></strong><br /> 
					<p class='blurb_target'>
						<a href="#">Show/hide blurb</a>
					</p>
				</div>
				<p class="blurb_content"><%= post.blurb %> <br /></p>
				<%= link_to 'Read Post', post %> <br>
			</td>
		</tr>
	<% end %>
</table>

app/views/posts/show.html.erb
<% meta :title => @post.title,
				:description => @post.blurb,
				:keywords => %w(rails ruby on rails Rails) 
%>

<p>
	<strong>Title:</strong> <%= @post.title %>
</p>

<p class='pull-left'>
	<%= image_tag @post.image_url.to_s %>
</p>
<p>
	<%= @post.content %>
</p>

<%= link_to 'Back', posts_path %>